from __future__ import absolute_import, division, print_function

from pkg_resources import DistributionNotFound, get_distribution

from . import calibrate
from .convert.api import open_raw
from .echodata.api import open_converted
from .echodata.combine import combine_echodata
from .process import Process  # noqa

try:
    VERSION = get_distribution(__name__).version
except DistributionNotFound:  # pragma: no cover
    try:
        from .version import version as VERSION  # noqa
    except ImportError:  # pragma: no cover
        raise ImportError(
            "Failed to find (autogenerated) version.py. "
            "This might be because you are installing from GitHub's tarballs, "
            "use the PyPI ones."
        )

__version__ = VERSION
__all__ = ["open_raw", "open_converted", "combine_echodata", "calibrate"]
